version: "2.1"
services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./db
    container_name: db1
    environment:
      - POSTGRES_PASSWORD
    healthcheck:
      test: /usr/local/bin/healthcheck.sh

  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app1
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./app/src:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    healthcheck:
      test: /usr/local/bin/healthcheck.sh

  test_runner:
    build:
      dockerfile: Dockerfile
      context: ./test_runner
    container_name: test_runner1
    depends_on:
      app:
        condition: service_healthy
